[package]
name = "community-oracle"
version = "0.1.0"
authors = ["Igor Aleksanov <popzxc@yandex.ru>"]
edition = "2018"

[dependencies]
actix-web = "3.0.0-alpha.3"
actix-rt = "1.1.1"
tokio = { version = "0.2", features = ["full"] }

serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.0"
